### ISSUE TITLE
PHP SDK is not working for latest version

### ISSUE THREAD

**Issue by nisan92** [directus/sdk-php#44]
I am using DIrectus version 7.7.0 where i can read and write data using postman through api, but when i am trying to fetch data using PHP SDK it throw an error that says `Unknwon Project API`,  well i am new user of directus , but as far i understand the request url for new version of directus is different like `https://[Project-url]/_/items/user_information` , When this php sdk trying to request at `https://[Project-url]/api/1.1/tables/client/rows`. So let me know if there any fix for that.

**Comment by shealavington** [comment]
Hey @nisan92 

We're aware that the PHP SDK Doesn't work for Directus 7, the `README.md` still mentions that this is `Directus 6 PHP SDK (Legacy)`, this hopefully clears up that the PHP SDK will not currently work for Directus 7, I recommend using Guzzle for now and call the API directly.

Unfortunately supporting many SDK's can be a resource heavy task that Directus just can't support at this time, however, if you'd like to follow the progress of SDK coverage, it might be best to follow this issue on the main Suite repository: https://github.com/directus/directus/issues/2255
